#include "Header_Assembler.h"

//repetitive if statements were mostly generated by AI
int Mnemonic_To_Opcode(char* mnemonic, int funct) {

    if (strcmp(mnemonic, "add") == 0) {
        if (funct == 1) return 0x20; // 100000
        return 0x00;                // 000000
    }
    if (strcmp(mnemonic, "addiu") == 0) {
        if (funct == 1) return -1;
        return 0x09;                // 001001
    }
    if (strcmp(mnemonic, "and") == 0) {
        if (funct == 1) return 0x24; // 100100
        return 0x00;                // 000000
    }
    if (strcmp(mnemonic, "andi") == 0) {
        if (funct == 1) return -1;
        return 0x0C;                // 001100
    }
    if (strcmp(mnemonic, "beq") == 0) {
        if (funct == 1) return -1;
        return 0x04;                // 000100
    }
    if (strcmp(mnemonic, "bne") == 0) {
        if (funct == 1) return -1;
        return 0x05;                // 000101
    }
    if (strcmp(mnemonic, "j") == 0) {
        if (funct == 1) return -1;
        return 0x02;                // 000010
    }
    if (strcmp(mnemonic, "lui") == 0) {
        if (funct == 1) return -1;
        return 0x0F;                // 001111
    }
    if (strcmp(mnemonic, "lw") == 0) {
        if (funct == 1) return -1;
        return 0x23;                // 100011
    }
    if (strcmp(mnemonic, "or") == 0) {
        if (funct == 1) return 0x25; // 100101
        return 0x00;                // 000000
    }
    if (strcmp(mnemonic, "ori") == 0) {
        if (funct == 1) return -1;
        return 0x0D;                // 001101
    }
    if (strcmp(mnemonic, "slt") == 0) {
        if (funct == 1) return 0x2A; // 101010
        return 0x00;                // 000000
    }
    if (strcmp(mnemonic, "sub") == 0) {
        if (funct == 1) return 0x22; // 100010
        return 0x00;                // 000000
    }
    if (strcmp(mnemonic, "sw") == 0) {
        if (funct == 1) return -1;
        return 0x2B;                // 101011
    }
    if (strcmp(mnemonic, "syscall") == 0) {
        if (funct == 1) return 0x0C; // 001100
        return 0x0C;                // 000000
    }

    return -1;
}

//repetitive if statements were mostly generated by AI
int Assembly_Name_To_Register(char* reg) {
    if (strcmp(reg, "$zero") == 0) return 0x00;
    if (strcmp(reg, "$at") == 0)   return 0x01;

    if (strcmp(reg, "$v0") == 0)   return 0x02;
    if (strcmp(reg, "$v1") == 0)   return 0x03;

    if (strcmp(reg, "$a0") == 0)   return 0x04;
    if (strcmp(reg, "$a1") == 0)   return 0x05;
    if (strcmp(reg, "$a2") == 0)   return 0x06;
    if (strcmp(reg, "$a3") == 0)   return 0x07;

    if (strcmp(reg, "$t0") == 0)   return 0x08;
    if (strcmp(reg, "$t1") == 0)   return 0x09;
    if (strcmp(reg, "$t2") == 0)   return 0x0A;
    if (strcmp(reg, "$t3") == 0)   return 0x0B;
    if (strcmp(reg, "$t4") == 0)   return 0x0C;
    if (strcmp(reg, "$t5") == 0)   return 0x0D;
    if (strcmp(reg, "$t6") == 0)   return 0x0E;
    if (strcmp(reg, "$t7") == 0)   return 0x0F;

    if (strcmp(reg, "$s0") == 0)   return 0x10;
    if (strcmp(reg, "$s1") == 0)   return 0x11;
    if (strcmp(reg, "$s2") == 0)   return 0x12;
    if (strcmp(reg, "$s3") == 0)   return 0x13;
    if (strcmp(reg, "$s4") == 0)   return 0x14;
    if (strcmp(reg, "$s5") == 0)   return 0x15;
    if (strcmp(reg, "$s6") == 0)   return 0x16;
    if (strcmp(reg, "$s7") == 0)   return 0x17;

    if (strcmp(reg, "$t8") == 0)   return 0x18;
    if (strcmp(reg, "$t9") == 0)   return 0x19;

    if (strcmp(reg, "$k0") == 0)   return 0x1A;
    if (strcmp(reg, "$k1") == 0)   return 0x1B;

    if (strcmp(reg, "$gp") == 0)   return 0x1C;
    if (strcmp(reg, "$sp") == 0)   return 0x1D;
    if (strcmp(reg, "$fp") == 0)   return 0x1E;
    if (strcmp(reg, "$ra") == 0)   return 0x1F;

    if (strchr(reg, '$')) {
        return Char_Array_To_Register(reg + 1);
    }

    return -1;
}

int Char_Array_To_Register(char* reg) {
    int result = 0;

    if (strstr(reg,"0x") != NULL) {
        for (int i = 2; i < (int)strlen(reg); i++) {

            if (reg[i] >= 48 && reg[i] <= 57) {
                result |= reg[i] - 48;
            }else if (reg[i] >= 65 && reg[i] <= 70) {
                result |= reg[i] - 54;
            }else if (reg[i] >= 97 && reg[i] <= 102) {
                result |= reg[i] - 87;
            }
            if (i < (int)strlen(reg) - 1)
                result <<= 4; //Don't shift on the final index
        }
    }else {
        for (int i = (int)strlen(reg) - 1 ; i >= 0 ; i--) {
            if (reg[i] == '-') continue;
            result += (reg[i] - 48) * (int)pow(10,(int)strlen(reg) - i - 1);
        }
        if (reg[0] == '-') {
            result ^= 0x0000ffff;
            result += 1;
        }
    }

    return result;
}

