//Edited with AI
#pragma once
#include <vector>
#include <string>
#include <unordered_map>
#include <cstdint>
#include <cstring>
#include <cstdio>
#include <cmath>

//Generated by AI

// ---- Utility_Methods.cpp ----
int Mnemonic_To_Opcode(char* mnemonic, int funct);
int Assembly_Name_To_Register(char* reg);
int Char_Array_To_Register(char* reg);

// ---- Assembler.cpp ----

// Data section helpers
std::vector<std::string> dataToHex(std::string line);
std::vector<std::string> flushDataHex();

// Tokenizer
std::vector<std::string> tokenize(std::string line);

// Pseudo-instruction expansion.
// dataLabels / textLabels are optional — pass nullptr (or omit) for pass-1 size counting.
std::vector<std::string> expandPseudo(const std::string& line,
                                      const std::unordered_map<std::string, uint32_t>* dataLabels = nullptr,
                                      const std::unordered_map<std::string, uint32_t>* textLabels = nullptr);

// Label resolution — rewrites label operands to numeric values before encoding.
// Returns a vector because memory-reference labels (lw/sw myLabel) expand into
// two instructions: lui $at, upper(addr) + lw/sw $rt, lower(addr)($at).
// currentPC is the byte address of the instruction being assembled.
std::vector<std::string> resolveLabels(const std::string& instr,
                                       const std::unordered_map<std::string, uint32_t>& textLabels,
                                       const std::unordered_map<std::string, uint32_t>& dataLabels,
                                       uint32_t currentPC);

// Core encoder
int instructionToHex(const char* mipsInstruction);
