//
// Created by thefi on 3/14/2026.
//
#include <iostream>
#include <fstream>
#include <string>
#include <unordered_map>
#include "Header_Assembler.h"

//Generated by AI, edited by boyajia4
int main(int args, char* argv[]) {
    if (args < 2) {
        std::cerr << "Usage: " << argv[0] << " <filename>" << std::endl;
        return 1;
    }

    std::ifstream input_file(argv[1]);
    if (!input_file.is_open()) {
        std::cerr << "Error: Could not open file " << argv[1] << std::endl;
        return 1;
    }

    std::string filename = argv[1];
    std::string base_name = filename;
    size_t last_dot = filename.find_last_of(".");
    if (last_dot != std::string::npos) {
        base_name = filename.substr(0, last_dot);
    }

    // =========================================================================
    // PASS 1: Build label tables
    // =========================================================================
    // Text labels map to their word index in the .text section (PC = 0x00400000 + index*4)
    // Data labels map to their byte address in the .data section (base = 0x10010000)
    std::unordered_map<std::string, uint32_t> textLabels; // label -> word address
    std::unordered_map<std::string, uint32_t> dataLabels; // label -> byte address

    static const uint32_t TEXT_BASE = 0x00400000;
    static const uint32_t DATA_BASE = 0x10010000;

    enum Section { NONE, DATA, TEXT };
    Section currentSection = NONE;

    uint32_t textWordIndex = 0;   // counts words emitted into .text
    uint32_t dataByteOffset = 0;  // counts bytes consumed in .data

    std::vector<std::string> rawLines; // store all non-empty, non-comment lines for pass 2

    std::string line;
    while (std::getline(input_file, line)) {
        if (line.empty()) continue;

        std::string trimmed = line;
        size_t first = trimmed.find_first_not_of(" \t\r\n");
        if (first == std::string::npos) continue;
        size_t last  = trimmed.find_last_not_of(" \t\r\n");
        trimmed = trimmed.substr(first, last - first + 1);

        // Strip inline comment for section/label detection only
        size_t cmt = trimmed.find('#');
        std::string noComment = (cmt != std::string::npos) ? trimmed.substr(0, cmt) : trimmed;
        // Trim noComment
        size_t nc_first = noComment.find_first_not_of(" \t");
        if (nc_first == std::string::npos) continue; // pure comment line
        size_t nc_last  = noComment.find_last_not_of(" \t");
        noComment = noComment.substr(nc_first, nc_last - nc_first + 1);

        if (noComment.empty()) continue;

        // Section headers
        if (noComment == ".data") { currentSection = DATA; rawLines.push_back(line); continue; }
        if (noComment == ".text") { currentSection = TEXT; rawLines.push_back(line); continue; }

        // Detect label(s) on this line.
        // A label may be alone on a line ("loop:") or share a line with an instruction ("loop: add $t0, $t1, $t2")
        std::string afterLabels = noComment;
        while (true) {
            size_t colonPos = afterLabels.find(':');
            if (colonPos == std::string::npos) break;

            // Verify nothing before the colon is a space/tab (label must be one token)
            std::string potentialLabel = afterLabels.substr(0, colonPos);
            size_t pl_first = potentialLabel.find_first_not_of(" \t");
            if (pl_first == std::string::npos) break;
            size_t pl_last  = potentialLabel.find_last_not_of(" \t");
            potentialLabel = potentialLabel.substr(pl_first, pl_last - pl_first + 1);

            // A label token must not contain spaces
            if (potentialLabel.find(' ') != std::string::npos ||
                potentialLabel.find('\t') != std::string::npos) break;

            // Register this label
            if (currentSection == TEXT) {
                textLabels[potentialLabel] = TEXT_BASE + textWordIndex * 4;
            } else if (currentSection == DATA) {
                dataLabels[potentialLabel] = DATA_BASE + dataByteOffset;
            }

            afterLabels = afterLabels.substr(colonPos + 1);
            size_t al_first = afterLabels.find_first_not_of(" \t");
            if (al_first == std::string::npos) { afterLabels = ""; break; }
            afterLabels = afterLabels.substr(al_first);
        }

        // If there's an instruction/data directive left, count its size
        if (!afterLabels.empty()) {
            if (currentSection == TEXT) {
                // Expand pseudo instructions to count the correct number of words
                std::vector<std::string> expanded = expandPseudo(afterLabels);
                textWordIndex += (uint32_t)expanded.size();
            } else if (currentSection == DATA) {
                // Only .asciiz supported right now; count its byte footprint
                size_t typeEnd = afterLabels.find_first_of(" \t");
                if (typeEnd != std::string::npos) {
                    std::string dtype = afterLabels.substr(0, typeEnd);
                    std::string ddata = afterLabels.substr(typeEnd + 1);
                    size_t fq = ddata.find_first_not_of(" \t");
                    if (fq != std::string::npos) ddata = ddata.substr(fq);

                    if (dtype == ".asciiz") {
                        size_t q1 = ddata.find('"');
                        size_t q2 = ddata.rfind('"');
                        if (q1 != std::string::npos && q2 > q1) {
                            std::string str = ddata.substr(q1 + 1, q2 - q1 - 1);
                            // Count logical characters, not raw chars (escape seqs = 1 byte)
                            uint32_t byteCount = 0;
                            for (size_t i = 0; i < str.size(); i++) {
                                if (str[i] == '\\' && i + 1 < str.size()) {
                                    char next = str[i+1];
                                    if (next=='n'||next=='t'||next=='r'||next=='0'||
                                        next=='\\'||next=='"') { i++; } // skip second char
                                }
                                byteCount++;
                            }
                            dataByteOffset += byteCount + 1; // +1 for null terminator
                        }
                    }
                }
            }
        }

        rawLines.push_back(line);
    }
    input_file.close();

    // =========================================================================
    // PASS 2: Emit output, resolving labels in instructions
    // =========================================================================
    std::ofstream data_file(base_name + ".data");
    std::ofstream text_file(base_name + ".text");

    if (!data_file.is_open() || !text_file.is_open()) {
        std::cerr << "Error: Could not create output files." << std::endl;
        return 1;
    }

    currentSection = NONE;
    uint32_t currentTextWordIndex = 0; // tracks current instruction's position for PC-relative calc

    for (const auto& rawLine : rawLines) {
        std::string trimmed = rawLine;
        size_t first = trimmed.find_first_not_of(" \t\r\n");
        if (first == std::string::npos) continue;
        size_t last  = trimmed.find_last_not_of(" \t\r\n");
        trimmed = trimmed.substr(first, last - first + 1);

        // Strip comment
        size_t cmt = trimmed.find('#');
        std::string noComment = (cmt != std::string::npos) ? trimmed.substr(0, cmt) : trimmed;
        size_t nc_first = noComment.find_first_not_of(" \t");
        if (nc_first == std::string::npos) continue;
        size_t nc_last  = noComment.find_last_not_of(" \t");
        noComment = noComment.substr(nc_first, nc_last - nc_first + 1);
        if (noComment.empty()) continue;

        // Section switches
        if (noComment == ".data") { currentSection = DATA; continue; }
        if (noComment == ".text") { currentSection = TEXT; continue; }

        // Strip label prefix(es) to get the bare instruction/directive
        std::string content = noComment;
        while (true) {
            size_t colonPos = content.find(':');
            if (colonPos == std::string::npos) break;
            std::string before = content.substr(0, colonPos);
            if (before.find(' ') != std::string::npos || before.find('\t') != std::string::npos) break;
            content = content.substr(colonPos + 1);
            size_t cf = content.find_first_not_of(" \t");
            if (cf == std::string::npos) { content = ""; break; }
            content = content.substr(cf);
        }

        if (content.empty()) continue; // label-only line

        if (currentSection == TEXT) {
            // Pass 2: expand pseudos WITH label maps so la/li resolve to real
            // addresses during expansion rather than emitting 0x0 placeholders.
            std::vector<std::string> instructions = expandPseudo(
                content, &dataLabels, &textLabels);

            for (const auto& instr : instructions) {
                // resolveLabels handles branches, jumps, and lw/sw label refs.
                // Returns a vector: 1 entry normally, 2 for lw/sw label expansion.
                std::vector<std::string> resolved = resolveLabels(
                    instr, textLabels, dataLabels,
                    TEXT_BASE + currentTextWordIndex * 4);

                for (const auto& resolvedInstr : resolved) {
                    int instructionHexValue = instructionToHex(resolvedInstr.c_str());
                    char hexString[12];
                    snprintf(hexString, sizeof(hexString), "%08x", instructionHexValue);
                    text_file << hexString << std::endl;
                    currentTextWordIndex++;
                }
            }

        } else if (currentSection == DATA) {
            std::vector<std::string> hexData = dataToHex(content);
            for (const auto& val : hexData) {
                data_file << val << std::endl;
            }
        }
    }

    // Flush any remaining data bytes
    std::vector<std::string> remainingData = flushDataHex();
    for (const auto& val : remainingData) {
        data_file << val << std::endl;
    }

    data_file.close();
    text_file.close();
    return 0;
}